# The workflow name
name: Update contributors

# Controls when the workflow will run
on: 
  push:
    paths:
      - "**/translations/**"
  pull_request:
    paths:
      - "**/translations/**"
  pull_request_target:
    paths:
      - "**/translations/**"

# The list of jobs this workflow executes
jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v14.6
        with:
          since_last_remote_commit: true
      - name: Create local changes
        run: |
          cd .github/scripts/update-contributors
          node index.js ${{ github.actor }} ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update contributors