# The workflow name
name: Update contributors

# Controls when the workflow will run
on: 
  push:
    branches:
      - main

# The list of jobs this workflow executes
jobs:
  update-contributors:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commit: ${{ github.event.commits }}
    if: ${{ matrix.commit.author.username == github.event.pusher.name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get changed files
        run: |
          echo "${{ matrix.id }}: ${{ matrix.message }}"
      # Test
      #    git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      #    echo "::set-output name=files::$(git log ${{ github.event.before }} ${{ github.sha }} --oneline --author=${{ github.author }} | xargs)"
      # - name: Output changed files
      #   run: |
      #     echo ${{ steps.getfiles.outputs.files }}
      # - name: Get changed files
      #   uses: tj-actions/changed-files@v14.6
      # - name: Create local changes
      #   run: |
      #     cd .github/scripts/update-contributors
      #     node index.js ${{ github.actor }} ${{ steps.changed-files.outputs.all_changed_files }}
      # - name: Commit files
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Update contributors
